name: Random Cron
on:
  workflow_run:
    workflows: ["刷步数"]
    types:
      - completed
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    env:
      NEXT: 'init'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
      - name: random cron
        run: |
          source cron_convert.sh
          echo "configuration CRON_HOURS ${{ vars.CRON_HOURS }}"
          persist_execute_log ${{ github.event_name }} ${{ vars.CRON_HOURS }}
          NEXT=$(inspect_next "$current_cron")
          echo "NEXT=${NEXT}" >> "$GITHUB_ENV"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          current=`TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S'`
          git commit -m "[${current}] random cron trigger by ${{ github.event_name }}"
          git push origin master
      - name: update flow name
        run: |
          echo "${NEXT}, ${{ env.NEXT }}, ${{ github.username }}, ${{ github.user }}, ${{ github.owner }}, ${{ github.repository }}, ${{ github.run_id }}"
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.username }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -d '{"name":"${{ env.NEXT }}"}'
